server:
  port: 8081

spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:7b
      embedding:
        enabled: true


milvus:
  config:
    ipAddr: localhost
    port: 19530